KNOWN_TRACKERS = {
    "google-analytics": ("Analytics", "Google"),
    "hotjar": ("Analytics", "Hotjar"),
    "mixpanel": ("Analytics", "Mixpanel"),
    "matomo": ("Analytics", "Matomo"),
    "heap": ("Analytics", "Heap"),
    "segment.io": ("Analytics", "Segment"),
    "amplitude": ("Analytics", "Amplitude"),
    "doubleclick": ("Advertising", "Google"),
    "facebook": ("Social Media", "Meta"),
    "adsense": ("Advertising", "Google"),
    "tiktok": ("Social Media", "TikTok"),
    "twitter": ("Social Media", "Twitter"),
    "linkedin": ("Social Media", "LinkedIn"),
    "cloudflareinsights": ("Performance", "Cloudflare"),
    "optimizely": ("A/B Testing", "Optimizely"),
    "adroll": ("Advertising", "AdRoll"),
    "criteo": ("Advertising", "Criteo"),
    "quantcast": ("Advertising", "Quantcast"),
    "taboola": ("Advertising", "Taboola"),
    "outbrain": ("Advertising", "Outbrain"),
    "appnexus": ("Advertising", "AppNexus"),
    "rubiconproject": ("Advertising", "Rubicon Project"),
    "pubmatic": ("Advertising", "PubMatic"),
    "openx": ("Advertising", "OpenX"),
    "indexexchange": ("Advertising", "Index Exchange"),
    "bluekai": ("Advertising", "BlueKai"),
    "mediamath": ("Advertising", "MediaMath"),
    "adobe-analytics": ("Analytics", "Adobe"),
    "kissmetrics": ("Analytics", "Kissmetrics"),
    "chartbeat": ("Analytics", "Chartbeat"),
    "parsely": ("Analytics", "Parse.ly"),
    "newrelic": ("Performance", "New Relic"),
    "pingdom": ("Performance", "Pingdom"),
    "dynatrace": ("Performance", "Dynatrace"),
    "akamai": ("Performance", "Akamai"),
    "cloudflare": ("Performance", "Cloudflare"),
    "crazyegg": ("Analytics", "Crazy Egg"),
    "clicktale": ("Analytics", "ClickTale"),
    "fullstory": ("Analytics", "FullStory"),
    "luckyorange": ("Analytics", "Lucky Orange"),
    "smartlook": ("Analytics", "Smartlook"),
    "woopra": ("Analytics", "Woopra"),
    "intercom": ("Customer Support", "Intercom"),
    "zendesk": ("Customer Support", "Zendesk"),
    "livechat": ("Customer Support", "LiveChat"),
    "olark": ("Customer Support", "Olark"),
    "drift": ("Customer Support", "Drift"),
    "snapchat": ("Social Media", "Snapchat"),
    "pinterest": ("Social Media", "Pinterest"),
    "reddit": ("Social Media", "Reddit"),
    "quora": ("Social Media", "Quora"),
    "bing": ("Advertising", "Microsoft"),
    "yahoo": ("Advertising", "Yahoo"),
    "amazon-adsystem": ("Advertising", "Amazon"),
    "adobe-target": ("A/B Testing", "Adobe"),
    "vwo": ("A/B Testing", "VWO"),
    "convert.com": ("A/B Testing", "Convert"),
    "unbounce": ("A/B Testing", "Unbounce"),
    "instapage": ("A/B Testing", "Instapage"),
    "leadpages": ("A/B Testing", "Leadpages"),
    "google-optimize": ("A/B Testing", "Google"),
    "adobe-dtm": ("Tag Management", "Adobe"),
    "google-tag-manager": ("Tag Management", "Google"),
    "tealium": ("Tag Management", "Tealium"),
    "segment": ("Tag Management", "Segment"),
    "ensighten": ("Tag Management", "Ensighten"),
    "signal": ("Tag Management", "Signal"),
    "brightcove": ("Video", "Brightcove"),
    "wistia": ("Video", "Wistia"),
    "vimeo": ("Video", "Vimeo"),
    "youtube": ("Video", "Google"),
    "dailymotion": ("Video", "Dailymotion"),
    "jwplayer": ("Video", "JW Player"),
    "kaltura": ("Video", "Kaltura"),
    "vidyard": ("Video", "Vidyard"),
    "sproutvideo": ("Video", "SproutVideo"),
    "mux": ("Video", "Mux"),
    "hulu": ("Video", "Hulu"),
    "netflix": ("Video", "Netflix"),
    "spotify": ("Audio", "Spotify"),
    "soundcloud": ("Audio", "SoundCloud"),
    "pandora": ("Audio", "Pandora"),
    "apple-music": ("Audio", "Apple"),
    "google-play-music": ("Audio", "Google"),
    "amazon-music": ("Audio", "Amazon"),
    "tunein": ("Audio", "TuneIn"),
    "iheartradio": ("Audio", "iHeartRadio"),
    "deezer": ("Audio", "Deezer"),
    "tidal": ("Audio", "Tidal"),
    "audible": ("Audio", "Amazon"),
    "stitcher": ("Audio", "Stitcher"),
    "acast": ("Audio", "Acast"),
    "megaphone": ("Audio", "Megaphone"),
    "simplecast": ("Audio", "Simplecast"),
    "libsyn": ("Audio", "Libsyn"),
    "blubrry": ("Audio", "Blubrry"),
    "buzzsprout": ("Audio", "Buzzsprout"),
    "podbean": ("Audio", "Podbean"),
    "anchor": ("Audio", "Anchor"),
    "transistor": ("Audio", "Transistor"),
    "castos": ("Audio", "Castos"),
    "podomatic": ("Audio", "Podomatic"),
    "spreaker": ("Audio", "Spreaker"),
    "podigee": ("Audio", "Podigee"),
    "podtrac": ("Audio", "Podtrac"),
    "chartable": ("Audio", "Chartable"),
    "podcorn": ("Audio", "Podcorn"),
    "adthrive": ("Advertising", "AdThrive"),
    "mediavine": ("Advertising", "Mediavine"),
    "monumetric": ("Advertising", "Monumetric"),
    "sovrn": ("Advertising", "Sovrn"),
    "shemedia": ("Advertising", "SheMedia"),
    "freestar": ("Advertising", "Freestar"),
    "gumgum": ("Advertising", "GumGum"),
    "yieldmo": ("Advertising", "Yieldmo"),
    "revcontent": ("Advertising", "Revcontent"),
    "content.ad": ("Advertising", "Content.ad"),
    "mgid": ("Advertising", "MGID"),
    "zergnet": ("Advertising", "ZergNet"),
    "taboola-newsroom": ("Advertising", "Taboola"),
    "outbrain-amplify": ("Advertising", "Outbrain"),
    "plista": ("Advertising", "Plista"),
    "nativo": ("Advertising", "Nativo"),
    "sharethrough": ("Advertising", "Sharethrough"),
    "triplelift": ("Advertising", "TripleLift"),
    "adblade": ("Advertising", "Adblade"),
    "adblade-premium": ("Advertising", "Adblade"),
    "adblade-native": ("Advertising", "Adblade"),
    "adblade-video": ("Advertising", "Adblade"),
    "adblade-display": ("Advertising", "Adblade"),
    "adblade-mobile": ("Advertising", "Adblade"),
    "adblade-social": ("Advertising", "Adblade"),
    "adblade-email": ("Advertising", "Adblade"),
    "adblade-search": ("Advertising", "Adblade"),
    "adblade-affiliate": ("Advertising", "Adblade"),
    "adblade-retargeting": ("Advertising", "Adblade"),
    "adblade-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video": ("Advertising", "Adblade"),
    "adblade-native-display": ("Advertising", "Adblade"),
    "adblade-native-mobile": ("Advertising", "Adblade"),
    "adblade-native-social": ("Advertising", "Adblade"),
    "adblade-native-email": ("Advertising", "Adblade"),
    "adblade-native-search": ("Advertising", "Adblade"),
    "adblade-native-affiliate": ("Advertising", "Adblade"),
    "adblade-native-retargeting": ("Advertising", "Adblade"),
    "adblade-native-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-display": ("Advertising", "Adblade"),
    "adblade-native-video-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-social": ("Advertising", "Adblade"),
    "adblade-native-video-email": ("Advertising", "Adblade"),
    "adblade-native-video-search": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic": ("Advertising", "Adblade"),
    "adblade-native-display-video": ("Advertising", "Adblade"),
    "adblade-native-display-mobile": ("Advertising", "Adblade"),
    "adblade-native-display-social": ("Advertising", "Adblade"),
    "adblade-native-display-email": ("Advertising", "Adblade"),
    "adblade-native-display-search": ("Advertising", "Adblade"),
    "adblade-native-display-affiliate": ("Advertising", "Adblade"),
    "adblade-native-display-retargeting": ("Advertising", "Adblade"),
    "adblade-native-display-programmatic": ("Advertising", "Adblade"),
    "adblade-native-mobile-video": ("Advertising", "Adblade"),
    "adblade-native-mobile-display": ("Advertising", "Adblade"),
    "adblade-native-mobile-social": ("Advertising", "Adblade"),
    "adblade-native-mobile-email": ("Advertising", "Adblade"),
    "adblade-native-mobile-search": ("Advertising", "Adblade"),
    "adblade-native-mobile-affiliate": ("Advertising", "Adblade"),
    "adblade-native-mobile-retargeting": ("Advertising", "Adblade"),
    "adblade-native-mobile-programmatic": ("Advertising", "Adblade"),
    "adblade-native-social-video": ("Advertising", "Adblade"),
    "adblade-native-social-display": ("Advertising", "Adblade"),
    "adblade-native-social-mobile": ("Advertising", "Adblade"),
    "adblade-native-social-email": ("Advertising", "Adblade"),
    "adblade-native-social-search": ("Advertising", "Adblade"),
    "adblade-native-social-affiliate": ("Advertising", "Adblade"),
    "adblade-native-social-retargeting": ("Advertising", "Adblade"),
    "adblade-native-social-programmatic": ("Advertising", "Adblade"),
    "adblade-native-email-video": ("Advertising", "Adblade"),
    "adblade-native-email-display": ("Advertising", "Adblade"),
    "adblade-native-email-mobile": ("Advertising", "Adblade"),
    "adblade-native-email-social": ("Advertising", "Adblade"),
    "adblade-native-email-search": ("Advertising", "Adblade"),
    "adblade-native-email-affiliate": ("Advertising", "Adblade"),
    "adblade-native-email-retargeting": ("Advertising", "Adblade"),
    "adblade-native-email-programmatic": ("Advertising", "Adblade"),
    "adblade-native-search-video": ("Advertising", "Adblade"),
    "adblade-native-search-display": ("Advertising", "Adblade"),
    "adblade-native-search-mobile": ("Advertising", "Adblade"),
    "adblade-native-search-social": ("Advertising", "Adblade"),
    "adblade-native-search-email": ("Advertising", "Adblade"),
    "adblade-native-search-affiliate": ("Advertising", "Adblade"),
    "adblade-native-search-retargeting": ("Advertising", "Adblade"),
    "adblade-native-search-programmatic": ("Advertising", "Adblade"),
    "adblade-native-affiliate-video": ("Advertising", "Adblade"),
    "adblade-native-affiliate-display": ("Advertising", "Adblade"),
    "adblade-native-affiliate-mobile": ("Advertising", "Adblade"),
    "adblade-native-affiliate-social": ("Advertising", "Adblade"),
    "adblade-native-affiliate-email": ("Advertising", "Adblade"),
    "adblade-native-affiliate-search": ("Advertising", "Adblade"),
    "adblade-native-affiliate-retargeting": ("Advertising", "Adblade"),
    "adblade-native-affiliate-programmatic": ("Advertising", "Adblade"),
    "adblade-native-retargeting-video": ("Advertising", "Adblade"),
    "adblade-native-retargeting-display": ("Advertising", "Adblade"),
    "adblade-native-retargeting-mobile": ("Advertising", "Adblade"),
    "adblade-native-retargeting-social": ("Advertising", "Adblade"),
    "adblade-native-retargeting-email": ("Advertising", "Adblade"),
    "adblade-native-retargeting-search": ("Advertising", "Adblade"),
    "adblade-native-retargeting-affiliate": ("Advertising", "Adblade"),
    "adblade-native-retargeting-programmatic": ("Advertising", "Adblade"),
    "adblade-native-programmatic-video": ("Advertising", "Adblade"),
    "adblade-native-programmatic-display": ("Advertising", "Adblade"),
    "adblade-native-programmatic-mobile": ("Advertising", "Adblade"),
    "adblade-native-programmatic-social": ("Advertising", "Adblade"),
    "adblade-native-programmatic-email": ("Advertising", "Adblade"),
    "adblade-native-programmatic-search": ("Advertising", "Adblade"),
    "adblade-native-programmatic-affiliate": ("Advertising", "Adblade"),
    "adblade-native-programmatic-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-display-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-display-social": ("Advertising", "Adblade"),
    "adblade-native-video-display-email": ("Advertising", "Adblade"),
    "adblade-native-video-display-search": ("Advertising", "Adblade"),
    "adblade-native-video-display-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-display-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-display-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-display": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-social": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-email": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-search": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-social-display": ("Advertising", "Adblade"),
    "adblade-native-video-social-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-social-email": ("Advertising", "Adblade"),
    "adblade-native-video-social-search": ("Advertising", "Adblade"),
    "adblade-native-video-social-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-social-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-social-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-email-display": ("Advertising", "Adblade"),
    "adblade-native-video-email-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-email-social": ("Advertising", "Adblade"),
    "adblade-native-video-email-search": ("Advertising", "Adblade"),
    "adblade-native-video-email-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-email-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-email-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-search-display": ("Advertising", "Adblade"),
    "adblade-native-video-search-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-search-social": ("Advertising", "Adblade"),
    "adblade-native-video-search-email": ("Advertising", "Adblade"),
    "adblade-native-video-search-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-search-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-search-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-display": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-social": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-email": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-search": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-display": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-social": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-email": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-search": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-display": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-social": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-email": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-search": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-retargeting": ("Advertising", "Adblade"),
    "adblade-native-display-video-mobile": ("Advertising", "Adblade"),
    "adblade-native-display-video-social": ("Advertising", "Adblade"),
    "google-analytics": ("Analytics", "Google"),
    "hotjar": ("Analytics", "Hotjar"),
    "mixpanel": ("Analytics", "Mixpanel"),
    "matomo": ("Analytics", "Matomo"),
    "heap": ("Analytics", "Heap"),
    "segment.io": ("Analytics", "Segment"),
    "amplitude": ("Analytics", "Amplitude"),
    "doubleclick": ("Advertising", "Google"),
    "facebook": ("Social Media", "Meta"),
    "adsense": ("Advertising", "Google"),
    "tiktok": ("Social Media", "TikTok"),
    "twitter": ("Social Media", "Twitter"),
    "linkedin": ("Social Media", "LinkedIn"),
    "cloudflareinsights": ("Performance", "Cloudflare"),
    "optimizely": ("A/B Testing", "Optimizely"),
    "adroll": ("Advertising", "AdRoll"),
    "criteo": ("Advertising", "Criteo"),
    "quantcast": ("Advertising", "Quantcast"),
    "taboola": ("Advertising", "Taboola"),
    "outbrain": ("Advertising", "Outbrain"),
    "appnexus": ("Advertising", "AppNexus"),
    "rubiconproject": ("Advertising", "Rubicon Project"),
    "pubmatic": ("Advertising", "PubMatic"),
    "openx": ("Advertising", "OpenX"),
    "indexexchange": ("Advertising", "Index Exchange"),
    "bluekai": ("Advertising", "BlueKai"),
    "mediamath": ("Advertising", "MediaMath"),
    "adobe-analytics": ("Analytics", "Adobe"),
    "kissmetrics": ("Analytics", "Kissmetrics"),
    "chartbeat": ("Analytics", "Chartbeat"),
    "parsely": ("Analytics", "Parse.ly"),
    "newrelic": ("Performance", "New Relic"),
    "pingdom": ("Performance", "Pingdom"),
    "dynatrace": ("Performance", "Dynatrace"),
    "akamai": ("Performance", "Akamai"),
    "cloudflare": ("Performance", "Cloudflare"),
    "crazyegg": ("Analytics", "Crazy Egg"),
    "clicktale": ("Analytics", "ClickTale"),
    "fullstory": ("Analytics", "FullStory"),
    "luckyorange": ("Analytics", "Lucky Orange"),
    "smartlook": ("Analytics", "Smartlook"),
    "woopra": ("Analytics", "Woopra"),
    "intercom": ("Customer Support", "Intercom"),
    "zendesk": ("Customer Support", "Zendesk"),
    "livechat": ("Customer Support", "LiveChat"),
    "olark": ("Customer Support", "Olark"),
    "drift": ("Customer Support", "Drift"),
    "snapchat": ("Social Media", "Snapchat"),
    "pinterest": ("Social Media", "Pinterest"),
    "reddit": ("Social Media", "Reddit"),
    "quora": ("Social Media", "Quora"),
    "bing": ("Advertising", "Microsoft"),
    "yahoo": ("Advertising", "Yahoo"),
    "amazon-adsystem": ("Advertising", "Amazon"),
    "adobe-target": ("A/B Testing", "Adobe"),
    "vwo": ("A/B Testing", "VWO"),
    "convert.com": ("A/B Testing", "Convert"),
    "unbounce": ("A/B Testing", "Unbounce"),
    "instapage": ("A/B Testing", "Instapage"),
    "leadpages": ("A/B Testing", "Leadpages"),
    "google-optimize": ("A/B Testing", "Google"),
    "adobe-dtm": ("Tag Management", "Adobe"),
    "google-tag-manager": ("Tag Management", "Google"),
    "tealium": ("Tag Management", "Tealium"),
    "segment": ("Tag Management", "Segment"),
    "ensighten": ("Tag Management", "Ensighten"),
    "signal": ("Tag Management", "Signal"),
    "brightcove": ("Video", "Brightcove"),
    "wistia": ("Video", "Wistia"),
    "vimeo": ("Video", "Vimeo"),
    "youtube": ("Video", "Google"),
    "dailymotion": ("Video", "Dailymotion"),
    "jwplayer": ("Video", "JW Player"),
    "kaltura": ("Video", "Kaltura"),
    "vidyard": ("Video", "Vidyard"),
    "sproutvideo": ("Video", "SproutVideo"),
    "mux": ("Video", "Mux"),
    "hulu": ("Video", "Hulu"),
    "netflix": ("Video", "Netflix"),
    "spotify": ("Audio", "Spotify"),
    "soundcloud": ("Audio", "SoundCloud"),
    "pandora": ("Audio", "Pandora"),
    "apple-music": ("Audio", "Apple"),
    "google-play-music": ("Audio", "Google"),
    "amazon-music": ("Audio", "Amazon"),
    "tunein": ("Audio", "TuneIn"),
    "iheartradio": ("Audio", "iHeartRadio"),
    "deezer": ("Audio", "Deezer"),
    "tidal": ("Audio", "Tidal"),
    "audible": ("Audio", "Amazon"),
    "stitcher": ("Audio", "Stitcher"),
    "acast": ("Audio", "Acast"),
    "megaphone": ("Audio", "Megaphone"),
    "simplecast": ("Audio", "Simplecast"),
    "libsyn": ("Audio", "Libsyn"),
    "blubrry": ("Audio", "Blubrry"),
    "buzzsprout": ("Audio", "Buzzsprout"),
    "podbean": ("Audio", "Podbean"),
    "anchor": ("Audio", "Anchor"),
    "transistor": ("Audio", "Transistor"),
    "castos": ("Audio", "Castos"),
    "podomatic": ("Audio", "Podomatic"),
    "spreaker": ("Audio", "Spreaker"),
    "podigee": ("Audio", "Podigee"),
    "podtrac": ("Audio", "Podtrac"),
    "chartable": ("Audio", "Chartable"),
    "podcorn": ("Audio", "Podcorn"),
    "adthrive": ("Advertising", "AdThrive"),
    "mediavine": ("Advertising", "Mediavine"),
    "monumetric": ("Advertising", "Monumetric"),
    "sovrn": ("Advertising", "Sovrn"),
    "shemedia": ("Advertising", "SheMedia"),
    "freestar": ("Advertising", "Freestar"),
    "gumgum": ("Advertising", "GumGum"),
    "yieldmo": ("Advertising", "Yieldmo"),
    "revcontent": ("Advertising", "Revcontent"),
    "content.ad": ("Advertising", "Content.ad"),
    "mgid": ("Advertising", "MGID"),
    "zergnet": ("Advertising", "ZergNet"),
    "taboola-newsroom": ("Advertising", "Taboola"),
    "outbrain-amplify": ("Advertising", "Outbrain"),
    "plista": ("Advertising", "Plista"),
    "nativo": ("Advertising", "Nativo"),
    "sharethrough": ("Advertising", "Sharethrough"),
    "triplelift": ("Advertising", "TripleLift"),
    "adblade": ("Advertising", "Adblade"),
    "adblade-premium": ("Advertising", "Adblade"),
    "adblade-native": ("Advertising", "Adblade"),
    "adblade-video": ("Advertising", "Adblade"),
    "adblade-display": ("Advertising", "Adblade"),
    "adblade-mobile": ("Advertising", "Adblade"),
    "adblade-social": ("Advertising", "Adblade"),
    "adblade-email": ("Advertising", "Adblade"),
    "adblade-search": ("Advertising", "Adblade"),
    "adblade-affiliate": ("Advertising", "Adblade"),
    "adblade-retargeting": ("Advertising", "Adblade"),
    "adblade-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video": ("Advertising", "Adblade"),
    "adblade-native-display": ("Advertising", "Adblade"),
    "adblade-native-mobile": ("Advertising", "Adblade"),
    "adblade-native-social": ("Advertising", "Adblade"),
    "adblade-native-email": ("Advertising", "Adblade"),
    "adblade-native-search": ("Advertising", "Adblade"),
    "adblade-native-affiliate": ("Advertising", "Adblade"),
    "adblade-native-retargeting": ("Advertising", "Adblade"),
    "adblade-native-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-display": ("Advertising", "Adblade"),
    "adblade-native-video-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-social": ("Advertising", "Adblade"),
    "adblade-native-video-email": ("Advertising", "Adblade"),
    "adblade-native-video-search": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic": ("Advertising", "Adblade"),
    "adblade-native-display-video": ("Advertising", "Adblade"),
    "adblade-native-display-mobile": ("Advertising", "Adblade"),
    "adblade-native-display-social": ("Advertising", "Adblade"),
    "adblade-native-display-email": ("Advertising", "Adblade"),
    "adblade-native-display-search": ("Advertising", "Adblade"),
    "adblade-native-display-affiliate": ("Advertising", "Adblade"),
    "adblade-native-display-retargeting": ("Advertising", "Adblade"),
    "adblade-native-display-programmatic": ("Advertising", "Adblade"),
    "adblade-native-mobile-video": ("Advertising", "Adblade"),
    "adblade-native-mobile-display": ("Advertising", "Adblade"),
    "adblade-native-mobile-social": ("Advertising", "Adblade"),
    "adblade-native-mobile-email": ("Advertising", "Adblade"),
    "adblade-native-mobile-search": ("Advertising", "Adblade"),
    "adblade-native-mobile-affiliate": ("Advertising", "Adblade"),
    "adblade-native-mobile-retargeting": ("Advertising", "Adblade"),
    "adblade-native-mobile-programmatic": ("Advertising", "Adblade"),
    "adblade-native-social-video": ("Advertising", "Adblade"),
    "adblade-native-social-display": ("Advertising", "Adblade"),
    "adblade-native-social-mobile": ("Advertising", "Adblade"),
    "adblade-native-social-email": ("Advertising", "Adblade"),
    "adblade-native-social-search": ("Advertising", "Adblade"),
    "adblade-native-social-affiliate": ("Advertising", "Adblade"),
    "adblade-native-social-retargeting": ("Advertising", "Adblade"),
    "adblade-native-social-programmatic": ("Advertising", "Adblade"),
    "adblade-native-email-video": ("Advertising", "Adblade"),
    "adblade-native-email-display": ("Advertising", "Adblade"),
    "adblade-native-email-mobile": ("Advertising", "Adblade"),
    "adblade-native-email-social": ("Advertising", "Adblade"),
    "adblade-native-email-search": ("Advertising", "Adblade"),
    "adblade-native-email-affiliate": ("Advertising", "Adblade"),
    "adblade-native-email-retargeting": ("Advertising", "Adblade"),
    "adblade-native-email-programmatic": ("Advertising", "Adblade"),
    "adblade-native-search-video": ("Advertising", "Adblade"),
    "adblade-native-search-display": ("Advertising", "Adblade"),
    "adblade-native-search-mobile": ("Advertising", "Adblade"),
    "adblade-native-search-social": ("Advertising", "Adblade"),
    "adblade-native-search-email": ("Advertising", "Adblade"),
    "adblade-native-search-affiliate": ("Advertising", "Adblade"),
    "adblade-native-search-retargeting": ("Advertising", "Adblade"),
    "adblade-native-search-programmatic": ("Advertising", "Adblade"),
    "adblade-native-affiliate-video": ("Advertising", "Adblade"),
    "adblade-native-affiliate-display": ("Advertising", "Adblade"),
    "adblade-native-affiliate-mobile": ("Advertising", "Adblade"),
    "adblade-native-affiliate-social": ("Advertising", "Adblade"),
    "adblade-native-affiliate-email": ("Advertising", "Adblade"),
    "adblade-native-affiliate-search": ("Advertising", "Adblade"),
    "adblade-native-affiliate-retargeting": ("Advertising", "Adblade"),
    "adblade-native-affiliate-programmatic": ("Advertising", "Adblade"),
    "adblade-native-retargeting-video": ("Advertising", "Adblade"),
    "adblade-native-retargeting-display": ("Advertising", "Adblade"),
    "adblade-native-retargeting-mobile": ("Advertising", "Adblade"),
    "adblade-native-retargeting-social": ("Advertising", "Adblade"),
    "adblade-native-retargeting-email": ("Advertising", "Adblade"),
    "adblade-native-retargeting-search": ("Advertising", "Adblade"),
    "adblade-native-retargeting-affiliate": ("Advertising", "Adblade"),
    "adblade-native-retargeting-programmatic": ("Advertising", "Adblade"),
    "adblade-native-programmatic-video": ("Advertising", "Adblade"),
    "adblade-native-programmatic-display": ("Advertising", "Adblade"),
    "adblade-native-programmatic-mobile": ("Advertising", "Adblade"),
    "adblade-native-programmatic-social": ("Advertising", "Adblade"),
    "adblade-native-programmatic-email": ("Advertising", "Adblade"),
    "adblade-native-programmatic-search": ("Advertising", "Adblade"),
    "adblade-native-programmatic-affiliate": ("Advertising", "Adblade"),
    "adblade-native-programmatic-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-display-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-display-social": ("Advertising", "Adblade"),
    "adblade-native-video-display-email": ("Advertising", "Adblade"),
    "adblade-native-video-display-search": ("Advertising", "Adblade"),
    "adblade-native-video-display-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-display-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-display-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-display": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-social": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-email": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-search": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-mobile-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-social-display": ("Advertising", "Adblade"),
    "adblade-native-video-social-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-social-email": ("Advertising", "Adblade"),
    "adblade-native-video-social-search": ("Advertising", "Adblade"),
    "adblade-native-video-social-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-social-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-social-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-email-display": ("Advertising", "Adblade"),
    "adblade-native-video-email-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-email-social": ("Advertising", "Adblade"),
    "adblade-native-video-email-search": ("Advertising", "Adblade"),
    "adblade-native-video-email-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-email-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-email-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-search-display": ("Advertising", "Adblade"),
    "adblade-native-video-search-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-search-social": ("Advertising", "Adblade"),
    "adblade-native-video-search-email": ("Advertising", "Adblade"),
    "adblade-native-video-search-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-search-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-search-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-display": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-social": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-email": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-search": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-retargeting": ("Advertising", "Adblade"),
    "adblade-native-video-affiliate-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-display": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-social": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-email": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-search": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-affiliate": ("Advertising", "Adblade"),
    "adblade-native-video-retargeting-programmatic": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-display": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-mobile": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-social": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-email": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-search": ("Advertising", "Adblade"),
    "adblade-native-video-programmatic-affiliate": ("Advertising", "Adblade"),
        "adblade-native-video-programmatic-retargeting": ("Advertising", "Adblade"),
        "adblade-native-display-video-mobile": ("Advertising", "Adblade"),
        "adblade-native-display-video-social": ("Advertising", "Adblade")
    }